version: '3.8'

services:
  # Development environment
  ticketflow-dev:
    build:
      context: .
      target: development
    ports:
      - "3001:3001"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_WEBHOOK_ENABLED=true
      - VITE_WEBHOOK_URL=https://api.usw2.pure.cloud/platform/api/v2/integrations/webhooks/407ea6a6f17305dad5ca10c33dbd2da5433dcdfe9c7e096dc9de0bf541c5a51c501d839441a7e9f1fe42f8add4ed6c84/events
    networks:
      - ticketflow-network
    profiles:
      - dev

  # Production environment
  ticketflow-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - VITE_WEBHOOK_ENABLED=false
    networks:
      - ticketflow-network
    profiles:
      - prod

  # Production environment with webhook enabled
  ticketflow-prod-webhook:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - VITE_WEBHOOK_ENABLED=true
      - VITE_WEBHOOK_URL=https://api.usw2.pure.cloud/platform/api/v2/integrations/webhooks/407ea6a6f17305dad5ca10c33dbd2da5433dcdfe9c7e096dc9de0bf541c5a51c501d839441a7e9f1fe42f8add4ed6c84/events
    networks:
      - ticketflow-network
    profiles:
      - prod-webhook

networks:
  ticketflow-network:
    driver: bridge 