services:
  # Backend API Server
  ticketflow-backend:
    image: johncarnell/ticketflow-backend:latest
    container_name: ticketflow-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - VITE_WEBHOOK_ENABLED=true
      - VITE_WEBHOOK_URL=https://api.usw2.pure.cloud/platform/api/v2/integrations/webhooks/9ae130307f25ce9d294f6891f38d04d36f44638f1e3cc59f85fcf0eef8bdcb5907a9434291c69c93ccabb6f598ba7fb4/events
      - VITE_WEBHOOK_TIMEOUT=5000
    networks:
      - ticketflow-network

  ticketflow-frontend:
    image: johncarnell/ticketflow-frontend:latest
    container_name: ticketflow-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=/rest
    networks:
      - ticketflow-network
    depends_on:
      - ticketflow-backend

   # Nginx Reverse Proxy
  nginx-proxy:
    image: nginx:alpine
    container_name: ticketflow-nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ticketflow-network
    depends_on:
      - ticketflow-backend
      - ticketflow-frontend    

networks:
  ticketflow-network:
    driver: bridge